# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Steps represent a sequence of tasks that will be executed as part of the job steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing packages
        run: npm ci

      - name: Installing ts-node globally
        run: npm i ts-node -g

      - name: Creating test data and running tests
        run: |
          npm test
        env:
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          PGHOST_TEST: postgres
          PGUSER_TEST: postgres
          PGPASSWORD_TEST: postgres
          PGDATABASE_TEST: postgres
